#!/usr/bin/env ruby

require 'fileutils'
require 'pathname'

SRC, DEST = ARGV
unless SRC && DEST
  abort "Usage: #{__FILE__} <src> <dest>"
end

FileUtils.rm_rf(DEST)

Pathname.glob("#{SRC}/*/index.mdx").map(&:cleanpath).each do |input_file|
  name = input_file.dirname.basename
  dest_dir = Pathname(DEST) / name
  # HACK: Use undocumented option `--basepath`.
  #       See https://github.com/jxnblk/mdx-deck/issues/368#issuecomment-494828254
  command = ['mdx-deck', 'build', input_file.to_s, '--out-dir', dest_dir.to_s, '--basepath', "/slides/#{name}"]
  puts "# #{input_file} -> #{dest_dir}"
  system(*command, exception: true)
end

Pathname.glob("#{SRC}/*/images").map(&:cleanpath).each do |image_dir|
  name = image_dir.dirname.basename
  dest_dir = Pathname(DEST) / name
  puts "# #{image_dir} -> #{dest_dir}"
  FileUtils.cp_r(image_dir, dest_dir)
  puts "done"
end
