name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    uses: ybiquitous/.github/.github/workflows/dependabot-auto-merge-reusable.yml@2fd29486ae4def771910ed448123404eeefdeef6 # main
    permissions:
      contents: write
