name: npm audit fix

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  npm-audit-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ybiquitous/npm-audit-fix-action@8d5eb3096dc8738e6dbac6a3e58402bb15da4f66 # v7.3.9
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
